# Generated by Django 3.1 on 2020-08-25 20:37

import COVIDdetection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient', models.CharField(max_length=20, unique=True)),
                ('docfile_beforeAnalysis', models.ImageField(upload_to=COVIDdetection.models.get_upload_path)),
                ('docfile_forModel', models.ImageField(upload_to=COVIDdetection.models.get_temp_path)),
                ('docfile_afterAnalysis', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=30)),
            ],
        ),
    ]
